#!/usr/bin/env bash
# Bash script to install and configure HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
server_config=\
"
frontend skomaiya_frontend
    bind *:80
    mode http
    default_backend skomaiya_backend
backend skomaiya_backend
    balance roundrobin
    server web-01 52.204.120.217:80 check
    server web-02 54.234.195.24:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy on startup
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Check the HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Reload HAProxy service
sudo service haproxy reload

# Confirm completion
echo "HAProxy configured to direct traffic to servers web-01 and web-02"
